require "bunny"
require "json"

require "publishing_platform_message_queue_consumer/version"
require "publishing_platform_message_queue_consumer/heartbeat_processor"
require "publishing_platform_message_queue_consumer/json_processor"
require "publishing_platform_message_queue_consumer/message"
require "publishing_platform_message_queue_consumer/message_consumer"
require "publishing_platform_message_queue_consumer/consumer"
